name: Test and Lint
on:
  pull_request:
    branches: [$master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest black isort mypy
          if [ -f requirements.txt]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest tests
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get repository
        uses: actions/checkout@v4
      - name: Sep up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest black isort mypy
          if [ -f requirements.txt]; then pip install -r requirements.txt; fi
      - name: Lint with mypy
        run: |
          mypy project/
      - name: Lint with black
        run: |
          black --diff --check project/
      - name: Lint with isort
        run: |
          isort --check-only --profile black project/
      - name: Lint with flake8
        run: |
          flake8 project/
        
          


